sudo: false
language: node_js

node_js:
  - "0.10"

notifications:
    email:
        - adriano.ueda@gmail.com

before_script:

  - curl -O http://dl.google.com/closure-compiler/compiler-latest.zip
  - mkdir build
  - unzip compiler-latest.zip compiler.jar -d build

  - npm install grunt --save-dev
  - npm install grunt-cli --save-dev
  - npm install grunt-contrib-qunit --save-dev
  - npm install grunt-closure-compiler --save dev

script:
  - grunt --verbose --force
